# Generated by Django 2.2 on 2021-06-02 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('Carryout', 'carryout'), ('Delivery', 'delivery')], default='Delivery', max_length=2)),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=6)),
                ('delivery_price', models.DecimalField(decimal_places=0, default=0, max_digits=6)),
                ('qty', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('favorite', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='pizza_app.User')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='pizza_app.User')),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(choices=[('VEGETERIAN', 'veggie'), ('PEPERONI', 'pepperoni'), ('MARGHERITA', 'margherita'), ('BARBEQUE', 'bbq'), ('HAWAII', 'hawaiian'), ('BUFFALO', 'buffalo'), ('SUPREME', 'supreme')], default='VEGETERIAN', max_length=2)),
                ('size', models.CharField(choices=[('LARGE', 'large'), ('NORMAL', 'normal'), ('SMALL', 'small')], default='NORMAL', max_length=2)),
                ('crust', models.CharField(choices=[('THIN CRUST', 'thin_crust'), ('THICK CRUST', 'thick_crust')], default='THIN CRUST', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pizza', to='pizza_app.Order')),
            ],
        ),
    ]
